# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Moments of Inspiration
email: momentsofinsight@gmail.com
description: > # this means to ignore newlines until "baseurl:"

  We have all experienced moments in our life when we feel inspired. These are moments when we feel inspired and feel that life is worth living. Moments, triggered by a piece of music, writing, poetry or a picture, we have an so many sources of inspiration.
  In this blog I will capture some of my moments of inspiration.
  In this blog you will find some of my moments of insight;
  I would love to discover yours.
baseurl: "/moments-of-inspiration" # the subpath of your site, e.g. /blog
url: "http://csmith111.github.io/" # the base hostname & protocol for your site
twitter_username: codesmith111
github_username:  csmith111


# Build settings
markdown: kramdown
